services:
  backend:
    build:
      context: ./backend
    env_file:
      - backend/.env
    ports:
      - "3001:3001"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    # Frontend is a static site served by Nginx
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped

networks:
  default:
    name: liift-kpis

